### ISSUE TITLE
Chat Preferences

### ISSUE THREAD

**Issue by romansavchuk** [filingroove/wavescore-chat#56]
New preferences with 3 tabs (but with inactive lang selector for now) http://take.ms/h3WiO

**Comment by filingroove** [comment]
![image](https://cloud.githubusercontent.com/assets/5341506/19510861/9267ed98-95ed-11e6-8635-375f251b63bc.png)

**Comment by filingroove** [comment]
Not closing this issue yet, because getting/setting this preferences is yet to be developed. But you can check the layout already at http://rundewoo.com/wavescore-phase-2/messaging.html

![screen shot 2016-10-19 at 10 32 23 pm](https://cloud.githubusercontent.com/assets/5341506/19534305/ee210846-964b-11e6-87c1-709b35fac7a0.png)

**Comment by romansavchuk** [comment]
1 - need animations when you serf between tabs.
2 - Autotranslate hide for now(but keep it in code)
3 -Brandwidth - make please segment-control of 3 items with quality. Segment control it's like this - http://take.ms/xnbhqk

**Comment by filingroove** [comment]
> 3 - Brandwidth - make please segment-control of 3 items with quality.

![screen shot 2016-10-20 at 7 08 14 pm](https://cloud.githubusercontent.com/assets/5341506/19568009/962fba62-96f8-11e6-914e-8580b18bf30a.png)

> 1 - need animations when you serf between tabs.

For v1 the tabs won't be there since there won't be any video/audio functionality. I'll focus on required functionality now.
